filebeat.inputs:
- type: docker
  containers.names:
    - "demo-transaction-banking"
  processors:
    - add_docker_metadata: ~
    - decode_json_fields:
        fields: ["message"]
        target: "json"
  multiline.pattern: '^\s'
  multiline.match: after

output.elasticsearch:
  hosts: ["http://109.123.234.206:9200"]
  username: "elastic"
  password: "LodplW_EZCRBo1E+f0tl"

setup.kibana:
  host: "http://109.123.234.206:5601"

logging.level: debug
logging.to_files: false
logging.to_stdout: true
