filebeat.inputs:
- type: log
  enabled: true
  paths:
    - /var/lib/docker/containers/*/*.log

processors:
  - add_host_metadata: ~
  - add_docker_metadata: ~

output.elasticsearch:
  hosts: ["http://aiops-elasticsearch:9200"]

setup.kibana:
  host: "http://aiops-kibana:5601"
