filebeat.inputs:
- type: container
  paths:
    - /var/lib/docker/containers/*/*.log
  processors:
    - add_docker_metadata: ~
    - decode_json_fields:
        fields: ["message"]
        target: "json"

output.elasticsearch:
  hosts: ["http://109.123.234.206:9200"]
  username: "elastic"
  password: "insignia123"

setup.kibana:
  host: "http://109.123.234.206:5601"
